id: A97CC4C2C
title: CVI_Verses 51-60
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.315876
  last_modified_at: 2022-03-01 23:27:39.315886
