id: A97CC4C2C
title: CV_Verses 41-50
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.415976
  last_modified_at: 2022-03-01 23:27:39.415982
