id: A97CC4C2C
title: CVI_Verses 11-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.231558
  last_modified_at: 2022-03-01 23:27:39.231564
