id: A97CC4C2C
title: CIII_Verses 61-70
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:37.121185
  last_modified_at: 2022-03-01 23:27:37.121189
