id: A97CC4C2C
title: CI_Verse 5
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:38.982563
  last_modified_at: 2022-03-01 23:27:38.982570
