id: A97CC4C2C
title: CIII_Verses 91-100
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:37.167596
  last_modified_at: 2022-03-01 23:27:37.167601
