id: A97CC4C2C
title: CV_Verses 1-10
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.361728
  last_modified_at: 2022-03-01 23:27:39.361735
