id: A97CC4C2C
title: CVII_Verses 51-56
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.196260
  last_modified_at: 2022-03-01 23:27:39.196270
