id: A97CC4C2C
title: CII_Verses 11-20
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:37.197008
  last_modified_at: 2022-03-01 23:27:37.197013
