id: A97CC4C2C
title: CII_Verses 21-30
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:37.209636
  last_modified_at: 2022-03-01 23:27:37.209640
