id: A97CC4C2C
title: CII_Verses 61-70
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:37.295536
  last_modified_at: 2022-03-01 23:27:37.295542
