id: A97CC4C2C
title: CVI_Verses 71-79
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.347574
  last_modified_at: 2022-03-01 23:27:39.347581
