id: A97CC4C2C
title: CVIII_Verses 31-39
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:39.063474
  last_modified_at: 2022-03-01 23:27:39.063479
