id: A97CC4C2C
title: CI_Verse 9
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:27:38.993339
  last_modified_at: 2022-03-01 23:27:38.993343
